test_that("SOA2plus_regulart", {
  set.seed(1234)
  temp <- SOA2plus_regulart(2, 4)
  expect_equal(dim(temp), c(16, 10))
  expect_false(ocheck(temp))
  set.seed(1234)
  temp <- SOA2plus_regulart(2, 4, m=5)
  expect_equal(dim(temp), c(16, 5))
  expect_true(ocheck(temp))
  set.seed(1234)
  temp <- SOA2plus_regulart(3, 3)
  expect_equal(dim(temp), c(27, 6))
  expect_true(ocheck(temp))
  set.seed(1234)
  temp <- SOA2plus_regulart(4, 3)
  expect_equal(dim(temp), c(64, 8))
  expect_true(ocheck(temp))
})
