# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on:
  push:
    paths:
      - 'README.Rmd'
      - 'man/SOAs-package.Rd'
    branches: [ main ]
    tags:
      - none
  workflow_dispatch:

name: Build-README

jobs:
  readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rmarkdown

      - name: Render README
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: commit README
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git diff --exit-code -s README.md && (echo "README.md has not changed from last push") || (git add README.md && git commit -m 'Automatic build of README.md' && git push)
