name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
#          - {os: macOS-latest, r: 'release'}
#          - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}

    steps:
      - name: Check out SOAs
        uses: actions/checkout@v2
        with:
          path: ./SOAs

      - name: Check out Development lhs
        uses: actions/checkout@v2
        with:
          repository: 'bertcarnell/lhs'
          ref: galoisfield
          path: ./lhs

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install lhs dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools"))
          remotes::install_deps(pkgdir = "lhs", dependencies = TRUE)
        shell: Rscript {0}

      - name: Install lhs
        run: |
          lhs_pack <- devtools::build("lhs", args = c("--no-build-vignettes"))
          install.packages(lhs_pack, repos = NULL)
        shell: Rscript {0}

      - name: Install SOAs dependencies
        run: |
          remotes::install_deps(pkgdir = "SOAs", dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck("SOAs", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
