name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: macOS-latest, r: 'release'}
          - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}

    steps:
      - name: Check out SOAs
        uses: actions/checkout@v2

      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R build Dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
        shell: Rscript {0}

      - name: Linux System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libgmp3-dev -y

      - name: MacOS System dependencies and source gmp
        # from the arrangements package github actions script
        if: runner.os == 'macOS'
        run: |
          brew install gmp
          Rscript -e "remotes::install_cran('gmp', type = 'source')"

      - name: Install SOAs dependencies
        run: |
          remotes::install_deps(pkgdir = ".", dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(".", args = c("--as-cran", "--no-manual"), error_on = "warning")
        shell: Rscript {0}

      - name: Code Coverage
        if: ${{ matrix.config.os }} == 'ubuntu-latest' && ${{ matrix.config.r }} == 'release'
        run: covr::codecov()
        shell: Rscript {0}

